# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 278)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.hint1_le = QtWidgets.QLineEdit(self.centralwidget)
        self.hint1_le.setObjectName("hint1_le")
        self.horizontalLayout.addWidget(self.hint1_le)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.hint2_le = QtWidgets.QLineEdit(self.centralwidget)
        self.hint2_le.setObjectName("hint2_le")
        self.horizontalLayout_2.addWidget(self.hint2_le)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.hint3_le = QtWidgets.QLineEdit(self.centralwidget)
        self.hint3_le.setObjectName("hint3_le")
        self.horizontalLayout_3.addWidget(self.hint3_le)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.answer_pte = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.answer_pte.setObjectName("answer_pte")
        self.verticalLayout.addWidget(self.answer_pte)
        self.copy_answer_btn = QtWidgets.QPushButton(self.centralwidget)
        self.copy_answer_btn.setObjectName("copy_answer_btn")
        self.verticalLayout.addWidget(self.copy_answer_btn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Пул май 2024"))
        self.label.setText(_translate("MainWindow", "Подсказка 1"))
        self.label_2.setText(_translate("MainWindow", "Подсказка 2"))
        self.label_3.setText(_translate("MainWindow", "Подсказка 3"))
        self.copy_answer_btn.setText(_translate("MainWindow", "Копировать ответ"))
