# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(661, 410)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.hint1_le = QtWidgets.QLineEdit(self.centralwidget)
        self.hint1_le.setObjectName("hint1_le")
        self.horizontalLayout.addWidget(self.hint1_le)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.hint2_le = QtWidgets.QLineEdit(self.centralwidget)
        self.hint2_le.setObjectName("hint2_le")
        self.horizontalLayout_2.addWidget(self.hint2_le)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.hint3_le = QtWidgets.QLineEdit(self.centralwidget)
        self.hint3_le.setObjectName("hint3_le")
        self.horizontalLayout_3.addWidget(self.hint3_le)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.answer_pte = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.answer_pte.setObjectName("answer_pte")
        self.verticalLayout.addWidget(self.answer_pte)
        self.copy_answer_btn = QtWidgets.QPushButton(self.centralwidget)
        self.copy_answer_btn.setObjectName("copy_answer_btn")
        self.verticalLayout.addWidget(self.copy_answer_btn)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.copy_hint = QtWidgets.QPushButton(self.centralwidget)
        self.copy_hint.setObjectName("copy_hint")
        self.horizontalLayout_5.addWidget(self.copy_hint)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sql_env_rb = QtWidgets.QRadioButton(self.centralwidget)
        self.sql_env_rb.setObjectName("sql_env_rb")
        self.horizontalLayout_4.addWidget(self.sql_env_rb)
        self.python_env_rb = QtWidgets.QRadioButton(self.centralwidget)
        self.python_env_rb.setObjectName("python_env_rb")
        self.horizontalLayout_4.addWidget(self.python_env_rb)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.hints_tv = QtWidgets.QTableView(self.centralwidget)
        self.hints_tv.setObjectName("hints_tv")
        self.verticalLayout_2.addWidget(self.hints_tv)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Пул май 2024"))
        self.label.setText(_translate("MainWindow", "Подсказка 1"))
        self.label_2.setText(_translate("MainWindow", "Подсказка 2"))
        self.label_3.setText(_translate("MainWindow", "Подсказка 3"))
        self.copy_answer_btn.setText(_translate("MainWindow", "Копировать ответ"))
        self.copy_hint.setText(_translate("MainWindow", "<"))
        self.sql_env_rb.setText(_translate("MainWindow", "SQL"))
        self.python_env_rb.setText(_translate("MainWindow", "Python"))
